
export const taskCategoriesData = [
  {
    name: "Mise en état et suivi de dossiers",
    tasks: [
      "Ouverture de dossier",
      "Constitution et demande de pièces",
      "Recherches juridiques",
      "Analyse de dossier",
      "Collecte et gestion des preuves",
      "Transfert ou cession de dossiers",
      "Dépôt et enrôlement d'acte de procédure",
      "Dépôt et suivi de correspondance",
      "Suivi des délais judiciaires",
      "(Re)programmation de dossier",
      "Voies de recours (appel, pourvoi)",
      "Clôture et archivage de dossier",
      "Archivage de dossier",
    ],
  },
  {
    name: "Conseil et assistance juridiques",
    tasks: [
      "Consultation et rédaction d'avis juridiques",
      "Rédaction d'actes juridiques",
      "Rédaction de note de synthèse",
      "Revue documentaire",
      "Analyse de conformité législative et réglementaire",
      "Veille législative et réglementaire",
    ],
  },
  {
    name: "Conseil et assistance judiciaires",
    tasks: [
      "Avis juridique ou note de synthèse",
      "Rédaction d'acte introductif d'instance",
      "Rédaction d'actes de procédure",
      "Dépôt et enrôlement d'actes de procédure",
      "Assistance à la Police judiciaire",
      "Assistance à parquet",
      "Assistance devant le Juge d'instruction ou la Chambre d'instruction",
      "Assistance devant autre organisme ou administration",
      "Audience de plaidoirie",
      "Compte rendu d'audience",
      "Compte rendu de suivi et de gestion de dossier",
      "Suivi des délais de procédure",
      "Collecte et gestion des preuves",
      "Voies de recours",
      "Médiation, arbitrage et règlement amiable",
      "Préparation d'audience ou de plaidoirie",
      "Assistance et représentation en justice",
      "Veille jurisprudentielle et législative",
    ],
  },
  {
    name: "Conseil et assistance fiscale",
    tasks: [
      "Conseil en fiscalité",
      "Contentieux fiscal et représentation devant les autorités fiscales",
      "Déclarations fiscales",
      "Assistance lors des contrôles fiscaux",
      "Audit de conformité fiscale",
    ],
  },
  {
    name: "Missions d'audit",
    tasks: [
      "Audit juridique de l'entreprise",
      "Audit de conformité",
      "Audit de sociétés (due diligence pré-acquisition)",
      "Audit fiscal",
      "Audit social",
    ],
  },
  {
    name: "Corporate (Droit des sociétés)",
    tasks: [
      "Création et dissolution de sociétés",
      "Rédaction et mise à jour des statuts et pactes d'actionnaires",
      "Tenue des registres légaux",
      "Rédaction et suivi des procès-verbaux d'assemblée générale",
      "Opérations sur capital",
      "Formalités auprès du RCCM et annonces légales",
    ],
  },
  {
    name: "Gestion des ressources humaines",
    tasks: [
      "Recrutement et intégration des collaborateurs",
      "Gestion de la paie, des congés et des absences",
      "Évaluations annuelles et gestion de carrière",
      "Plan de formation interne et continue",
      "Rédaction et gestion des contrats de travail",
      "Gestion des procédures de licenciement",
    ],
  },
  {
    name: "Secrétariat & Administration",
    tasks: [
      "Gestion de l'agenda et des plannings",
      "Gestion du courrier et des envois",
      "Gestion des fournitures et des achats",
      "Maintenance des locaux et logistique interne",
      "Gestion des contrats avec les fournisseurs et prestataires",
      "Traduction certifiée",
      "Formalités notariales et légalisations",
    ],
  },
  {
    name: "Comptabilité & Finance",
    tasks: [
      "Émission et suivi des factures d'honoraires",
      "Suivi des encaissements et des relances",
      "Gestion des avances et des dépôts",
      "Rapprochement comptable",
      "Prévisions budgétaires",
      "Déclaration et paiement des charges",
      "Gestion du parc automobile du cabinet",
    ],
  },
  {
    name: "Communication & Développement",
    tasks: [
      "Veille et développement commercial",
      "Rédaction de propositions commerciales",
      "Suivi des appels d'offres",
      "Organisation d'événements et de conférences",
      "Rédaction de contenu pour le site web et les réseaux sociaux",
    ],
  },
  {
    name: "Community management",
    tasks: [
      "Gestion des réseaux sociaux",
      "Diffusion de veille juridique externe",
      "Valorisation de l'image du cabinet",
      "Suivi e-réputation et réponses digitales",
    ],
  },
  {
    name: "Relations avec experts et tiers",
    tasks: [
      "Coordination avec huissiers, notaires, experts judiciaires",
      "Transmission d'acte pour signification",
      "Demande de constat",
      "Transmission d'acte pour authentification",
      "Suivi des rapports d'expertise",
      "Gestion des consultants et experts externes",
    ],
  },
  {
    name: "Conformité & Risques",
    tasks: [
      "Mise en place des procédures KYC (Know Your Customer) et LCB-FT (Lutte Contre le Blanchiment de capitaux et le Financement du Terrorisme)",
      "Conformité législative et réglementaire, et protection des données",
      "Audit de conformité interne",
      "Gestion des incidents de sécurité et des fuites de données",
      "Gestion des risques opérationnels",
    ],
  },
  {
    name: "Gestion Documentaire",
    tasks: [
      "Numérisation, classement et indexation des documents",
      "Mise à jour des modèles et templates de documents",
      "Archivage et destruction programmée des dossiers",
      "Sauvegarde et sécurisation des données",
    ],
  },
  {
    name: "IT & Systèmes d'Information",
    tasks: [
      "Support informatique interne",
      "Sauvegarde des données et systèmes",
      "Gestion des accès et des droits utilisateurs",
      "Sécurité informatique et gestion des incidents",
    ],
  },
];
