#!/bin/bash
# 🧪 Test Visuel : Filtrage et Compteurs de Catégories

echo "🎯 TEST RAPIDE - FILTRAGE CATÉGORIES"
echo "===================================="
echo ""
echo "📍 Ouvrir l'application : http://localhost:3002/"
echo ""
echo "✅ CHECKLIST VISUELLE"
echo "-------------------"
echo ""
echo "[ ] 1. Aller sur l'onglet 'Documents'"
echo "[ ] 2. Vérifier menu gauche : 8 catégories affichées"
echo "[ ] 3. Vérifier 'Tous les documents' a icône FileText (document)"
echo "[ ] 4. Vérifier autres catégories ont icône Folder (dossier)"
echo "[ ] 5. Vérifier chaque catégorie affiche un compteur à droite"
echo "[ ] 6. Cliquer sur 'Contrats' → vérifier style actif bleu"
echo "[ ] 7. Vérifier liste filtrée = uniquement contrats"
echo "[ ] 8. Cliquer sur 'Tous les documents' → liste complète"
echo "[ ] 9. Taper dans recherche + sélectionner catégorie → filtre combiné"
echo ""
echo "🎨 RENDU ATTENDU"
echo "---------------"
echo ""
echo "État ACTIF (cliqué) :"
echo "  [📄] Tous les documents        [142]"
echo "  └─ Fond bleu, texte blanc, ombre"
echo ""
echo "État INACTIF :"
echo "  [📁] Contrats                  [45]"
echo "  [📁] Factures                  [28]"
echo "  └─ Fond gris au survol, texte slate-300"
echo ""
echo "🔍 COMPTEURS"
echo "-----------"
echo "Formule : count = nombre documents par catégorie"
echo "Tous = total global"
echo "Autres catégories = filtrées par document_category"
echo ""
echo "💡 SI COMPTEURS = 0 PARTOUT"
echo "-------------------------"
echo "→ Aller dans Supabase Dashboard"
echo "→ Vérifier que tasks_files.document_category est rempli"
echo ""
echo "Requête SQL :"
echo "SELECT document_category, COUNT(*)"
echo "FROM tasks_files"
echo "GROUP BY document_category;"
echo ""
echo "🚀 LANCER L'APP"
echo "--------------"
echo "npm run dev"
echo ""
