#!/bin/bash
# Test rapide : Affichage catégories + Synchronisation

echo "🧪 TEST RAPIDE : CATÉGORIES & SYNCHRONISATION"
echo "=============================================="
echo ""

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "📋 CHECKLIST VISUELLE"
echo "--------------------"
echo ""

echo "1️⃣ Affichage Catégories dans Documents"
echo "   ${YELLOW}Action${NC}: Ouvrir l'onglet Documents"
echo "   ${YELLOW}Vérifier${NC}: Badge bleu avec catégorie sous chaque nom de fichier"
echo "   ${YELLOW}Exemple${NC}: \"contrat.pdf\""
echo "              \"⚫ Pièces\" (en bleu)"
echo ""

echo "2️⃣ Affichage Catégories dans Tâches"
echo "   ${YELLOW}Action${NC}: Ouvrir une tâche avec fichiers attachés"
echo "   ${YELLOW}Vérifier${NC}: Catégorie affichée à côté de la taille"
echo "   ${YELLOW}Exemple${NC}: \"📁 document.pdf\""
echo "              \"125 KB  ⚫ Courriers\" (en bleu)"
echo ""

echo "3️⃣ Synchronisation Upload Tâche → Documents"
echo "   ${YELLOW}Action${NC}:"
echo "   - Créer un dossier (ex: \"Dossier Test\")"
echo "   - Créer une tâche liée à ce dossier"
echo "   - Uploader un fichier dans la tâche"
echo "   - Aller dans Documents"
echo "   ${YELLOW}Vérifier${NC}: Fichier visible dans Documents avec:"
echo "   • Le bon nom"
echo "   • La catégorie (si définie)"
echo "   • Lien vers le dossier"
echo ""

echo "4️⃣ Colonne document_category en Base"
echo "   ${YELLOW}Action${NC}: Ouvrir Supabase Dashboard > SQL Editor"
echo "   ${YELLOW}Requête${NC}:"
echo "   SELECT column_name, data_type, is_nullable"
echo "   FROM information_schema.columns"
echo "   WHERE table_name = 'tasks_files'"
echo "   AND column_name = 'document_category';"
echo ""
echo "   ${YELLOW}Résultat attendu${NC}:"
echo "   column_name       | data_type | is_nullable"
echo "   document_category | text      | YES"
echo ""

echo "5️⃣ Index Performance"
echo "   ${YELLOW}Requête${NC}:"
echo "   SELECT indexname FROM pg_indexes"
echo "   WHERE tablename = 'tasks_files'"
echo "   AND indexname = 'idx_tasks_files_document_category';"
echo ""
echo "   ${YELLOW}Résultat attendu${NC}:"
echo "   indexname"
echo "   idx_tasks_files_document_category"
echo ""

echo "6️⃣ Trigger Synchronisation avec Catégorie"
echo "   ${YELLOW}Requête${NC}:"
echo "   SELECT trigger_name, event_manipulation"
echo "   FROM information_schema.triggers"
echo "   WHERE trigger_name = 'trigger_sync_task_file_to_case';"
echo ""
echo "   ${YELLOW}Résultat attendu${NC}:"
echo "   trigger_name                    | event_manipulation"
echo "   trigger_sync_task_file_to_case | INSERT"
echo ""

echo "✅ TESTS À COCHER"
echo "----------------"
echo "[ ] 1. Badge catégorie visible dans Documents"
echo "[ ] 2. Badge catégorie visible dans fichiers de Tâches"
echo "[ ] 3. Catégorie affichée en bleu avec point rond"
echo "[ ] 4. Upload tâche → Document apparaît dans Documents"
echo "[ ] 5. Catégorie préservée lors synchronisation"
echo "[ ] 6. Colonne document_category existe en base"
echo "[ ] 7. Index idx_tasks_files_document_category créé"
echo "[ ] 8. Trigger trigger_sync_task_file_to_case actif"
echo ""

echo "📊 REQUÊTES DE DEBUG"
echo "-------------------"
echo ""

echo "-- Voir tous documents avec catégories"
echo "SELECT"
echo "  file_name,"
echo "  document_category,"
echo "  CASE"
echo "    WHEN task_id IS NOT NULL AND case_id IS NOT NULL THEN 'Task+Case'"
echo "    WHEN task_id IS NOT NULL THEN 'Task'"
echo "    WHEN case_id IS NOT NULL THEN 'Case'"
echo "  END as link_type"
echo "FROM tasks_files"
echo "ORDER BY created_at DESC"
echo "LIMIT 10;"
echo ""

echo "-- Compter documents par catégorie"
echo "SELECT"
echo "  document_category,"
echo "  COUNT(*) as count"
echo "FROM tasks_files"
echo "GROUP BY document_category"
echo "ORDER BY count DESC;"
echo ""

echo "🚀 EXÉCUTION"
echo "-----------"
echo "1. Assurez-vous que les migrations SQL sont appliquées:"
echo "   - sql/add_document_category_to_tasks_files.sql"
echo "   - sql/sync_documents_tasks_cases.sql"
echo ""
echo "2. Relancez le serveur:"
echo "   npm run dev"
echo ""
echo "3. Testez visuellement les points ci-dessus"
echo ""
echo "4. Validez les requêtes SQL dans Supabase Dashboard"
echo ""
